import OnScreenKeyboardKeymapLayout from "@type/on-screen-keyboard-keymap-layout.type";

const STANDARD_KEYMAP: OnScreenKeyboardKeymapLayout = [
	[
		["`", "~", 1],
		["1", "!", 1],
		["2", "@", 1],
		["3", "#", 1],
		["4", "$", 1],
		["5", "%", 1],
		["6", "^", 1],
		["7", "&", 1],
		["8", "*", 1],
		["9", "(", 1],
		["0", ")", 1],
		["-", "_", 1],
		["=", "+", 1],
		["backspace", null, 2],
	],
	[
		["tab", null, 1.5],
		["q", "Q", 1],
		["w", "W", 1],
		["e", "E", 1],
		["r", "R", 1],
		["t", "T", 1],
		["y", "Y", 1],
		["u", "U", 1],
		["i", "I", 1],
		["o", "O", 1],
		["p", "P", 1],
		["[", "{", 1],
		["]", "}", 1],
		["\\", "|", 1.5],
	],
	[
		["capslock", null, 1.75],
		["a", "A", 1],
		["s", "S", 1],
		["d", "D", 1],
		["f", "F", 1],
		["g", "G", 1],
		["h", "H", 1],
		["j", "J", 1],
		["k", "K", 1],
		["l", "L", 1],
		[";", ":", 1],
		["'", '"', 1],
		["enter", null, 2.25],
	],
	[
		["shift", null, 2.25],
		["z", "Z", 1],
		["x", "X", 1],
		["c", "C", 1],
		["v", "V", 1],
		["b", "B", 1],
		["n", "N", 1],
		["m", "M", 1],
		[",", "<", 1],
		[".", ">", 1],
		["/", "?", 1],
		["shift_", null, 2.75],
	],
	[
		[null, null, 3.75],
		["space", null, 6.25],
		[null, null, 3.75],
	],
];
export default STANDARD_KEYMAP;
