name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Volta to setup Node and NPM
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Compile
        run: |
          npm run build -- -- --x64 --arm64 --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List build directory
        run: |
          ls dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Console-UI
          path: dist/**
